### PR TITLE
Create change-networks.md

### PR DESCRIPTION
**Pull request by GeekyLumberjack**
This is a basic example to explain the switching of networks using the unlock-protocol configuration

### CODE REVIEW

**Comment by julien51** [comment]
Amazing! Thanks for working on this. Ideally do you think that rather than create a whole new page you could update this one? https://github.com/unlock-protocol/docs/blob/master/getting-started/locking-page.md

**Comment by GeekyLumberjack** [comment]
@julien51 I've made the requested changes. You're right thats a better spot.

**Review by julien51 — APPROVED** [review]
💯

**Comment by julien51** [comment]
Thank you *very* much!

**Pull request merged**
