### PR TITLE
Reorganize contract api docs

### PR DESCRIPTION
**Pull request by clemsos**
This is a first (manual) pass at #41 to reorganize contract API docs a bit, ans make things consistent before scripting it

### CODE REVIEW

**Comment by julien51** [comment]
I can't build this one locally. :/
Apparently it makes a lot of 404

**Review by ChialiTsai — APPROVED** [review]
good to have the latest and archive folder

**Comment by julien51** [comment]
>  We could disable those checks at the risk of some broken links.

I think they are really useful/helpful!

**Comment by clemsos** [comment]
> I can't build this one locally. :/
> 
> Apparently it makes a lot of 404

Hmmm weird. I had a bunch of 404 warnings on first build attempt but it still build correctly for me

**Review by julien51 — APPROVED** [review]

**Comment by julien51** [comment]
So it does build but has a LOT of 404 warnings like these

```
[WARNING] Docs markdown link couldn't be resolved: (../../tutorials/using-subgraphs.md) in /Users/julien/repos/docs/docs/Tools/Locksmith/webhooks.md for version current
[WARNING] Docs markdown link couldn't be resolved: (/paywall/configuring-checkout.md) in /Users/julien/repos/docs/docs/Basics/README.md for version current
```

That needs to be fixed before we ship

**Pull request merged**
