### PR TITLE
feat: Move to docusaurus

### PR DESCRIPTION
**Pull request by searchableguy**
This PR moves our docs from gitbook to docusaurus. 

Checklist before merging

- [x] Disable the gitbook sync so it doesn't cause any issues.

### CODE REVIEW

**Comment by searchableguy** [comment]
Why the old unmaintained GTM plugin?

I already enabled Google analytics support in the file which uses our ID.

**Comment by julien51** [comment]
>  Why add the old unmaintained GTM plugin?

I understand last update is from 2 years ago, but I am not sure we can say it's unmaintained?

> I already enabled Google analytics support in the config file which uses our ID. Facebook maintains Google analytics plugin which is enabled in the theme settings.

We should not be using GA directly but GTM. Do you think the "built" in GA stuff works with GTM?

**Comment by searchableguy** [comment]
> We should not be using GA directly but GTM. Do you think the "built" in GA stuff works with GTM?


Yes, it does. Google analytics by default collect predefined metrics and events for reports. GTM on the other hand is more explicit way of tagging certain events (user going through a particular user journey) and pushing that event data for report generation. 

If we don't have any specialised requirements or events tagged, then GA would do.

GTM is also fine if you tag all necessary events from the dashboard or inside code itself.

**Review by julien51 — APPROVED** [review]
Let's ship it!

**Comment by searchableguy** [comment]
Next time let's squash the PR because otherwise it results in very messy history.

**Pull request merged**
