### PR TITLE
Fixes #254 fixed checkout navigation

### LINKED ISSUE #254: Tools: Checkout
Checkout nav is broken

### PR DESCRIPTION
**Pull request by wonderwomancode**

### CODE REVIEW

**Review by julien51 — CHANGES_REQUESTED** [review]
I think we're missing the content from tools/checkout/README ?

**Review by ccarfi — APPROVED** [review]
i clicked approve before seeing julien's question above

**Comment by julien51** [comment]
Screen Shot 2022-12-09 at 2 42 13 PM
Please update screenshot!

**Review by julien51 — APPROVED** [review]
I love your logo :D

**Pull request merged**
