### PR TITLE
Openapi info generated from @unlock-protocol/locksmith@0.0.4

### PR DESCRIPTION
**Pull request by searchableguy**
This PR updates openapi.yml file from the unlock-monorepo.

### CODE REVIEW

**Comment by julien51** [comment]
Can we add links to and from this?

**Review by wonderwomancode — APPROVED** [review]
Looks like this is complete now. I don't think we have a ticket opened for the next steps but let's get one added.

**Comment by julien51** [comment]
@wonderwomancode Please wait a bit... @searchableguy is adding links to and from this because this is not in the "main" nav.

**Comment by searchableguy** [comment]
I will do that in another PR because this is not a manual PR. It's generated using script. Safe to merge if everything looks good.

**Comment by wonderwomancode** [comment]
> 

Yes, that's what I assumed based on prior conversation, hence the comment about opening a ticket so we don't forget.

**Comment by julien51** [comment]
ok let's do it then!

**Review by julien51 — APPROVED** [review]

**Pull request merged**
