### PR TITLE
Hardhat Plugin documentation

### PR DESCRIPTION
**Pull request by clemsos**
Basic documentation about the new Unlock hardhat plugin

### CODE REVIEW

**Comment by clemsos** [comment]
Maybe the link to the example repo should be more prominent there.

**Comment by julien51** [comment]
Assigning to @timfalls :)

**Review by timfalls — APPROVED** [review]
LGTM

**Comment by clemsos** [comment]
thx @timfalls 

@julien51 is Gitbook deploying these github PRs ? or is there extra steps we should take to make this live?

**Pull request merged**
