### PR TITLE
Amit — what is a smart contract

### PR DESCRIPTION
**Pull request by ccarfi**
Original draft from contractor writer here:
https://www.notion.so/unlockprotocol/What-is-a-smart-contract-db82046b26f34816a1543796c9d06cdd

This required considerable editing.

### CODE REVIEW

**Comment by ccarfi** [comment]
@searchableguy @wonderwomancode @julien51 is there any documentation on deploying new content via docusaurus? not sure why this is failing.

**Comment by searchableguy** [comment]
Don't worry about it.

I fixed it in another PR, will update master. 

It failed to build due to an overaggressive
url validation in config file.

**Comment by searchableguy** [comment]
https://github.com/unlock-protocol/docs/blob/master/docusaurus.config.js#L32

Remove the part after # in the url here. Your build will pass.

**Comment by ccarfi** [comment]
@searchableguy i don't see where that needs to be changed in this branch.

**Comment by searchableguy** [comment]
It's a file you will see locally in your branch.

**Comment by ccarfi** [comment]
@searchableguy have 100% always done everything here through the browser UI here on github.com UI. don't have a local repo folder AFAIK, & have never used/had to use one previously.

**Comment by searchableguy** [comment]
Oh, I didn't realise. Don't worry about it then. I will take care of deployment issue.

**Comment by ccarfi** [comment]
thanks. what needs to be updated so we can deploy content into docs without manual intervention?

**Pull request merged**
